### ISSUE TITLE
Add More Languages / Features

### ISSUE THREAD

**Issue by bionicles** [bionicles/tree_plus#7]
# TODO Languages 
- [ ] Metal
- [ ] WGSL
- [ ] Agda
- [ ] Delphi
- [ ] Groovy
- [ ] Coq
- [ ] ??? (Your idea here, please feel welcome to comment)

# TODO Databases
- [ ] PostgreSQL
- [ ] MySQL
- [ ] Redis / Valkey

Process for each:
- [ ] Add a test file
- [ ] Add a test expectation to `tests/test_more_languages.py`
- [ ] Add a `parse_XYZ(contents: str) -> list[str]:` function to `src/parse_file.py`
- [ ] Invoke `parse_XYZ` from the main reducer function atop `src/parse_file.py`
- [ ] Run `make debug` and debug the new test until it works
